# Generated by Django 3.1.4 on 2020-12-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201206_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bookshelf name')),
                ('description', models.TextField(verbose_name='Bookshelf description')),
                ('image', models.ImageField(default='book.png', upload_to='books')),
            ],
        ),
    ]
