# Generated by Django 3.1.4 on 2020-12-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201226_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='more',
            name='desc',
            field=models.TextField(default=1, verbose_name='More description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='more',
            name='link',
            field=models.TextField(verbose_name='More link'),
        ),
    ]
