# Generated by Django 3.1.4 on 2020-12-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201226_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='more',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='More description'),
        ),
    ]
